Skyscanner/stylelint-config-skyscanner

.travis.yml

I was wondering was `udo` was all about, checked it with the Travis CI linter and noticed that it's probably supposed to be `sudo` :)

Fix typo in Travis configuration

---

CHANGELOG.md
index.js

This disables `no-descending-specificity` for now. We felt that it was introducing too much disruption for little gain.

Disabled no-descending-specificity rule

---

CHANGELOG.md
package-lock.json
package.json

Added prettier dependency to style lint as this can cause an error that prettier is not available in projects that are running just `stylelint-config-sksyscanner` and not `eslint-config-skyscanner`

Adding prettier dependency

---

package-lock.json
package.json

Adding the `stylelint-plugin-backpack` lib to this repo so that we don't forget to add in the future. The current version does not have any code so has no effect right now, but means that dependabot will be able to monitor future versions as we develop the plugin.

[BPK-4015]: Add Backpack plugin dep ahead of development

---

.spelling
CHANGELOG.md
README.md
index.js

`unit-blacklist` was deprecated in [stylelint v13.7.0](https://github.com/stylelint/stylelint/blob/13.7.0/CHANGELOG.md#1370).

Replace "unit-blacklist" with "unit-disallowed-list"

---

index.js
index.test.js
package-lock.json
package.json

`prettier` is an explicit dependency, although `eslint-config-skyscanner` also includes it, and this can create a missmatch and require multiple versions.
I think we can remove the explicit dependency and rely only in the one installed by `eslint-config-skyscanner`.

Remove Prettier as dependency

---

CHANGELOG.md
index.js
index.test.js

Temporarily disabling Backpack stylelint plugin due to issues with false positives when running

[NO JIRA]: Disable Backpack stylelint plugin

---

UNRELEASED.md
docs/migration-from-4-to-5.md
index.js
index.test.js
package-lock.json
package.json

`stylelint` >14 has a [security vulnerability](https://security.snyk.io/vuln/SNYK-JS-STYLELINT-1585622) that requires updating to 14 to fix.
This PR updates to 14, and updates all dependencies to be compatible.
It will be a major version release.
A beta has been produced from this PR, currently `@skyscanner/stylelint-config-skyscanner@5.0.0-beta.4`.
The release notes for the version updates included in the initial `v5` update be seen below:
- [`stylelint v14`](https://github.com/stylelint/stylelint/releases/tag/14.0.0)
- [`stylelint-config-prettier v9`](https://github.com/prettier/stylelint-config-prettier/releases/tag/v9.0.0)
- [`stylelint-order v5`](https://github.com/hudochenkov/stylelint-order/releases/tag/5.0.0)
- [`stylelint-prettier v2`]()
- [`stylelint-declaration-strict-value …

Update to Stylelint 14

---

UNRELEASED.md
index.js
index.test.js

This [`stylelint` bump](https://github.com/Skyscanner/stylelint-config-skyscanner/pull/170) included a change to use `currentcolor` instead of `currentColor` (adding a config to keep the old name).
Our `scale-unlimited/declaration-strict-value` only allows `currentColor`, so currently it's not possible to use `currentcolor` nor `currentColor`.
Allowing both in `scale-unlimited/declaration-strict-value` will allow clients to use the default one (`currentcolor` ) or the legacy one (`currentColor`).
See more context about `currentcolor` change in the `stylelint` [pr discussion](https://github.com/stylelint/stylelint/pull/5849) and the [original issue](https://github.com/stylelint/stylelint/issues/4884).

Allow "currentcolor"

---

README.md
UNRELEASED.md
index.js
index.test.js
package-lock.json
package.json

This PR introduces the Backpack stylelint plugin and enables the `use-typography-styles` rule as a warning. This is to encourage the use of Backpack mixins in typography.

[KOA-4901] Enable typography rule

---

package.json

`@skyscanner/stylelint-plugin-backpack` is a plugin used in the config, so it must be a dependency instead of a devdependency.
Otherwise this error is displayed when running the linter:
```
Error: Could not find "@skyscanner/stylelint-plugin-backpack". Do you need a `configBasedir`?
```

Move "stylelint-plugin-backpack" from "devDependencies" to "dependencies"

---

.github/workflows/ci.yml
CONTRIBUTING.md
package-lock.json
package.json

This library was last published 5years ago and looks to have a few security vulnerabilities - as this is providing low benefit of ensuring spelling, I think for the security benefit we can manually review these and be cautious instead

Remove markdown-spellchecker

---

package-lock.json
package.json

To properly support in other node18 projects, Upgrading stylelint-config to work with 16 and above.

 Upgrade node version to support 18 / hydrogen

---

CHANGELOG.md
UNRELEASED.md
docs/eslint-as-dependency.md

`eslint-config-skyscanner` major version bumps should trigger a major version of `stylelint-config-skyscanner`. We decided this a long time ago, but in https://github.com/Skyscanner/stylelint-config-skyscanner/pull/255 I forgot.
This PR sets up for deprecating the latest release, https://github.com/Skyscanner/stylelint-config-skyscanner/commit/bfe68009639abfddf148b94a4bc2ceb165dcec11, releasing a `7.0.0` version, and adds some documentation so we don't have to pick through old PRs to remember this.

Add docs around ECS affect on versions, prepare 7.0.0 release

---

UNRELEASED.md
package-lock.json
package.json

Follows on from https://github.com/Skyscanner/eslint-config-skyscanner/pull/565.
This triggers a major version bump of @skyscanner/stylelint-config-skyscanner due to https://github.com/Skyscanner/stylelint-config-skyscanner/blob/main/docs/eslint-as-dependency.md.

[KOA-6213] Update @skyscanner/eslint-config-skyscanner to v14.0.0

---

UNRELEASED.md
package-lock.json
package.json

Brings in https://github.com/Skyscanner/eslint-config-skyscanner/releases/tag/v15.0.0.
This will be a major release due to: https://github.com/Skyscanner/stylelint-config-skyscanner/blob/main/docs/eslint-as-dependency.md

[KOA-6217] Bump to eslint-config-skyscanner v15, which comes with eslint 8

---

CHANGELOG.md
UNRELEASED.md
docs/release.md
index.js
index.test.js
package-lock.json
package.json

This moves us to  Stylelint v15 and Prettier 3. The former is a prerequisite of the latter.
Prerequisites of this PR are moving `stylelint-plugin-backpack` to Stylelint v15, and `eslint-config-skyscanner` to Prettier v3.
The combination of all of these has been tested using:
- @skyscanner/stylelint-plugin-backpack@3.0.0-beta.1
- @skyscanner/eslint-config-skyscanner@15.2.0-beta.0
-  @skyscanner/stylelint-config-skyscanner@10.0.0-beta.1
See author annotations for explanations of removals and additions.
https://prettier.io/blog/2023/07/05/3.0.0.html
https://stylelint.io/migration-guide/to-15/

[KOA-6224] Update to Stylelint v15 and Prettier v3

---

index.js

The side effects of `media-feature-range-notation` at _build_ time were missed in 
https://github.com/Skyscanner/stylelint-config-skyscanner/pull/293.
The deprecation of `block-closing-brace-newline-after` was missed from checking this list: https://stylelint.io/user-guide/rules#deprecated
https://stylelint.io/user-guide/rules/block-closing-brace-newline-after/

[KOA-6224] Adjust non-compatible rules

---

index.js

Context
`at-import-no-partial-leading-underscore` has been deprecated in favour of load-no-partial-leading-underscore. We should update our index.js to use load-no-partial-leading-underscore.
For context on change see https://github.com/stylelint-scss/stylelint-scss/pull/867
Docs for - `at-import-no-partial-leading-underscore` https://github.com/stylelint-scss/stylelint-scss/blob/v5.2.1/src/rules/at-import-no-partial-leading-underscore/README.md
Doc for `load-no-partial-leading-underscore` https://github.com/stylelint-scss/stylelint-scss/blob/d245813e783cc3cb3f8f946cc293a041202b995e/src/rules/load-no-partial-leading-underscore/README.md
The change includes a new potential warning
`@use "sass:meta";
.a {
@include meta.load-css("_fff", $with: ("border-contrast": true));
}`

Replaced depreacted at-import-no-partial-leading-underscore

---

.github/workflows/release.yml

The latest release workflow failed as the repo is using a deprecated actions/cache version that GitHub bails out of running. This PR updates to a newer version.
https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down

Update to actions/cache v4.2.0

---

.nvmrc
index.js
index.test.js
package-lock.json
package.json

Upgrades to stylelint v16 and associated dependencies.
- Upgrades stylelint to v16
- Replaces rule `scss/at-import-partial-extension` with `scss/load-partial-extension` with same triggering.
- This may now cause an increase in errors in projects (although you maybe ok from the previous rule as it works in the exact same way) as it looks to fix some issues the old rule was not reporting/false positives. If you do get errors with this version, to fix this, you will simply need to update any SCSS `@import` or `@use` to include the file extension
```
// Before
@import 'styles'
// or 
@use 'styles'
// After
@import 'styles.scss'
// or
@use 'styles.scss'
```
- Associated major bumps which drop support for Stylelint versions lower than v16
- Converts to support ESM
- Upgrades to minimum v22 Node …

[LOOM-1906]: Stylelint 16 upgrade

---

index.js

Set load-partial-extension rule to `never`. This ensures that _no_ Sass import uses file extensions.
In the previous version of stylelint-config-skyscanner we were using a different plugin that was set to `always` require file extensions in imports. However, it was broken and was not failing despite not using extensions.
- the linting rule can automatically fix the errors if the plugin is set to `never` require the extension. If set to `always` this isn't possible and requires manual changes, or a custom script to update imports throughout the codebase. This means easier adoption for consumers.
- if importing CSS, you _must not_ use the extension
-  source: https://sass-lang.com/documentation/at-rules/import/#importing-css
- Sass documentation does not recommend a way of doing, nor does …

Set load-partial-extension rule to never
